// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geidzcdxveylhizpogjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlaWR6Y2R4dmV5bGhpenBvZ2p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMTMyMzgsImV4cCI6MjA1NjY4OTIzOH0.fGejaTVC18rPZWmbpPZWELMuxWpx2YGh-txQkrueoQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);